#!/usr/bin/env python3
"""Generate the canonical VCS NTSC palette for every gbtrace VCS adapter.

A GOLD (frame) test's verdict is a captured frame compared against a golden
reference. The pixels a VCS adapter stores are TIA colour codes (the COLUxx
byte, 0..254 even) — emulator-independent. The palette (colour code -> RGB) is
NOT: each emulator ships slightly different RGB. So the SUITE declares ONE
canonical palette and every adapter embeds it, so `gbtrace render` produces the
identical golden PNG no matter which oracle captured the trace.

Canonical NTSC palette = Stella's `ourNTSCPalette` (the de-facto community
standard). 128 hue/luma colours indexed by (colour code >> 1). We emit a
256-entry RGB table indexed by the raw colour byte: even index = the colour,
odd index = black (TIA ignores bit 0, and 0xFF is our blank/vblank sentinel, so
it must render black too).

Run from adapters/:  python3 genpalette.py
"""
import os

# 128 canonical NTSC colours (Stella ourNTSCPalette, even entries). Provenance
# is recorded in the suite notes; change here + regenerate to re-declare it.
NTSC_128 = [
    0x000000,0x4a4a4a,0x6f6f6f,0x8e8e8e,0xaaaaaa,0xc0c0c0,0xd6d6d6,0xececec,
    0x484800,0x69690f,0x86861d,0xa2a22a,0xbbbb35,0xd2d240,0xe8e84a,0xfcfc54,
    0x7c2c00,0x904811,0xa26221,0xb47a30,0xc3903d,0xd2a44a,0xdfb755,0xecc860,
    0x901c00,0xa33915,0xb55328,0xc66c3a,0xd5824a,0xe39759,0xf0aa67,0xfcbc74,
    0x940000,0xa71a1a,0xb83232,0xc84848,0xd65c5c,0xe46f6f,0xf08080,0xfc9090,
    0x840064,0x97197a,0xa8308f,0xb846a2,0xc659b3,0xd46cc3,0xe07cd2,0xec8ce0,
    0x500084,0x68199a,0x7d30ad,0x9246c0,0xa459d0,0xb56ce0,0xc57cee,0xd48cfc,
    0x140090,0x331aa3,0x4e32b5,0x6848c6,0x7f5cd5,0x956fe3,0xa980f0,0xbc90fc,
    0x000094,0x181aa7,0x2d32b8,0x4248c8,0x545cd6,0x656fe4,0x7580f0,0x8490fc,
    0x001c88,0x183b9d,0x2d57b0,0x4272c2,0x548ad2,0x65a0e1,0x75b5ef,0x84c8fc,
    0x003064,0x185080,0x2d6d98,0x4288b0,0x54a0c5,0x65b7d9,0x75cceb,0x84e0fc,
    0x004030,0x18624e,0x2d8169,0x429e82,0x54b899,0x65d1ae,0x75e7c2,0x84fcd4,
    0x004400,0x1a661a,0x328432,0x48a048,0x5cba5c,0x6fd26f,0x80e880,0x90fc90,
    0x143c00,0x355f18,0x527e2d,0x6e9c42,0x87b754,0x9ed065,0xb4e775,0xc8fc84,
    0x303800,0x505916,0x6d762b,0x88923e,0xa0ab4f,0xb7c25f,0xccd86e,0xe0ec7c,
    0x482c00,0x694d14,0x866a26,0xa28638,0xbb9f47,0xd2b656,0xe8cc63,0xfce070,
]
assert len(NTSC_128) == 128

# 256-entry RGB table: even = colour, odd = black.
RGB = []
for i in range(256):
    c = NTSC_128[i >> 1] if (i & 1) == 0 else 0x000000
    RGB += [(c >> 16) & 0xFF, (c >> 8) & 0xFF, c & 0xFF]

HERE = os.path.dirname(os.path.abspath(__file__))
BANNER = "// Generated by adapters/genpalette.py — do not edit. Canonical VCS\n" \
         "// NTSC palette (Stella ourNTSCPalette). 256*3 bytes, index = TIA\n" \
         "// colour byte; even = colour, odd = black (bit 0 ignored / blank).\n"


def emit_go(path):
    body = ",".join(str(b) for b in RGB)
    with open(path, "w") as f:
        f.write(BANNER)
        f.write("\npackage main\n\n")
        f.write("var canonicalNTSCPalette = [768]byte{" + body + "}\n")


def emit_c(path):
    rows = []
    for r in range(0, len(RGB), 24):
        rows.append("  " + ",".join(str(b) for b in RGB[r:r + 24]) + ",")
    with open(path, "w") as f:
        f.write(BANNER)
        f.write("\n#pragma once\n#include <cstdint>\n\n")
        f.write("static const uint8_t canonicalNTSCPalette[768] = {\n")
        f.write("\n".join(rows) + "\n};\n")


emit_go(os.path.join(HERE, "gopher2600", "ntsc_palette.go"))
emit_go(os.path.join(HERE, "mame", "ntsc_palette.go"))
emit_c(os.path.join(HERE, "stella", "ntsc_palette.h"))
print("wrote gopher2600/ntsc_palette.go, mame/ntsc_palette.go, stella/ntsc_palette.h")
