#!/usr/bin/env python3
"""Generate mame_palette.go: MAME's actual a2600 NTSC RGB for each TIA code.

MAME's palette differs from the suite's canonical palette, so the adapter can't
map MAME's rendered pixels back to TIA codes by nearest-canonical. This runs the
calib_colors ROM (each code as a solid scanline) through MAME, reads MAME's RGB
for every code, and writes them as a Go table the adapter reverse-maps against
exactly. Re-run if the installed MAME version changes.

  python3 gen_mame_palette.py
"""
import os, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ASM = os.path.join(HERE, "calib_colors.asm")

LUA = '''
local n=0
emu.register_frame_done(function()
  n=n+1; if n<12 then return end
  local s=manager.machine.screens:at(1)
  local ok,px=pcall(function() return s:pixels() end)
  if ok then local f=io.open("%s","wb"); f:write(px); f:close()
    io.stderr:write(string.format("GBFRAME %%d %%d\\n", s.width, s.height)) end
  manager.machine:exit()
end)
'''


def main():
    tmp = tempfile.mkdtemp(prefix="mame-calib-")
    rom = os.path.join(tmp, "calib.bin")
    r = subprocess.run(["dasm", ASM, "-f3",
                        "-I/usr/include/dasm/atari2600",
                        f"-o{rom}"], capture_output=True, text=True)
    if not os.path.exists(rom):
        print("dasm failed:\n" + r.stdout + r.stderr); return 1

    dump = os.path.join(tmp, "px.bin")
    lua = os.path.join(tmp, "cap.lua")
    open(lua, "w").write(LUA % dump)
    home = os.path.join(tmp, "home"); os.makedirs(home)
    subprocess.run(["pkill", "-9", "-x", "mame"], capture_output=True)
    p = subprocess.run(["mame", "a2600", "-cart", rom, "-video", "none",
                        "-sound", "none", "-nothrottle", "-autoboot_script", lua,
                        "-autoboot_delay", "0", "-cfg_directory", home,
                        "-snapshot_directory", home, "-nvram_directory", home,
                        "-seconds_to_run", "3"],
                       capture_output=True, text=True, timeout=60)
    subprocess.run(["pkill", "-9", "-x", "mame"], capture_output=True)
    w = h = 0
    for ln in p.stderr.splitlines():
        if ln.startswith("GBFRAME "):
            _, ws, hs = ln.split(); w, h = int(ws), int(hs)
    if not os.path.exists(dump) or w == 0:
        print("no frame dumped:\n" + p.stderr[-500:]); return 1
    argb = open(dump, "rb").read()

    def px(x, y):  # (r,g,b) at raw pixel
        i = (y * w + x) * 4
        return argb[i+2], argb[i+1], argb[i]

    col = w // 2                       # middle column (inside the visible area)
    nonblack = lambda y: any(px(col, y))
    active = next((y for y in range(h) if nonblack(y)), None)
    if active is None:
        print("no active row found"); return 1

    # 256-entry RGB table; code 0 and all odd codes are black.
    rgb = bytearray(256 * 3)
    for L in range(0, 127):            # lines 0..126 -> codes 2,4,..,254
        code = (L + 1) * 2
        r_, g_, b_ = px(col, active + L)
        rgb[code*3], rgb[code*3+1], rgb[code*3+2] = r_, g_, b_

    body = ",".join(str(b) for b in rgb)
    out = os.path.join(HERE, "mame_palette.go")
    with open(out, "w") as f:
        f.write("// Generated by gen_mame_palette.py — do not edit. MAME's actual\n"
                "// a2600 NTSC RGB per TIA colour code (256*3 bytes; index = colour\n"
                "// byte; odd/0 = black). Used to reverse-map MAME's pixels to codes.\n\n"
                "package main\n\n"
                "var mamePaletteRGB = [768]byte{" + body + "}\n")
    print(f"wrote {out} (active row {active}, {w}x{h})")
    # sanity: code 2 should be a dark grey, code 14 ($0E) near-white
    print("  code $02:", tuple(rgb[2*3:2*3+3]), " code $0E:", tuple(rgb[14*3:14*3+3]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
