#!/usr/bin/env python3
"""Generate mame_palette.go: MAME's actual a2600 NTSC RGB for each TIA code.

MAME's palette differs from the suite's canonical palette, so the adapter can't
map MAME's rendered pixels back to TIA codes by nearest-canonical. This runs the
calib_colors ROM (each code as a solid scanline) through MAME, reads MAME's RGB
for every code, and writes them as a Go table the adapter reverse-maps against
exactly. Re-run if the installed MAME version changes.

  python3 gen_mame_palette.py
"""
import os, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ASM = os.path.join(HERE, "calib_colors.asm")

LUA = '''
local n=0
emu.register_frame_done(function()
  n=n+1; if n<12 then return end
  local s=manager.machine.screens:at(1)
  local ok,px=pcall(function() return s:pixels() end)
  if ok then local f=io.open("%s","wb"); f:write(px); f:close()
    io.stderr:write(string.format("GBFRAME %%d %%d\\n", s.width, s.height)) end
  manager.machine:exit()
end)
'''


def calibrate(machine, rom, tmp):
    """Render the colour-ramp ROM through one MAME machine and return its 256*3
    RGB table (MAME's actual colour per TIA code) — code 0 / odd codes black."""
    dump = os.path.join(tmp, f"px_{machine}.bin")
    lua = os.path.join(tmp, f"cap_{machine}.lua")
    open(lua, "w").write(LUA % dump)
    home = os.path.join(tmp, f"home_{machine}"); os.makedirs(home, exist_ok=True)
    subprocess.run(["pkill", "-9", "-x", "mame"], capture_output=True)
    p = subprocess.run(["mame", machine, "-cart", rom, "-video", "none",
                        "-sound", "none", "-nothrottle", "-autoboot_script", lua,
                        "-autoboot_delay", "0", "-cfg_directory", home,
                        "-snapshot_directory", home, "-nvram_directory", home,
                        "-seconds_to_run", "3"],
                       capture_output=True, text=True, timeout=60)
    subprocess.run(["pkill", "-9", "-x", "mame"], capture_output=True)
    w = h = 0
    for ln in p.stderr.splitlines():
        if ln.startswith("GBFRAME "):
            _, ws, hs = ln.split(); w, h = int(ws), int(hs)
    if not os.path.exists(dump) or w == 0:
        raise RuntimeError(f"{machine}: no frame dumped\n" + p.stderr[-400:])
    argb = open(dump, "rb").read()

    def px(x, y):
        i = (y * w + x) * 4
        return argb[i+2], argb[i+1], argb[i]

    col = w // 2
    active = next((y for y in range(h) if any(px(col, y))), None)
    if active is None:
        raise RuntimeError(f"{machine}: no active row")
    rgb = bytearray(256 * 3)
    for L in range(0, 128):            # lines 0..127 -> codes 2,4,..,254,0
        code = ((L + 1) * 2) & 0xFF    # L=127 -> code 0 (MAME's own "black")
        rgb[code*3], rgb[code*3+1], rgb[code*3+2] = px(col, active + L)
    print(f"  {machine}: active row {active}, {w}x{h}; "
          f"$02={tuple(rgb[6:9])} $0E={tuple(rgb[42:45])}")
    return rgb


def main():
    tmp = tempfile.mkdtemp(prefix="mame-calib-")
    rom = os.path.join(tmp, "calib.bin")
    r = subprocess.run(["dasm", ASM, "-f3", "-I/usr/include/dasm/atari2600",
                        f"-o{rom}"], capture_output=True, text=True)
    if not os.path.exists(rom):
        print("dasm failed:\n" + r.stdout + r.stderr); return 1

    tables = {}
    for machine, var in (("a2600", "mamePaletteRGB"), ("a2600p", "mamePalPaletteRGB")):
        try:
            tables[var] = calibrate(machine, rom, tmp)
        except Exception as e:
            print("ERROR:", e); return 1

    out = os.path.join(HERE, "mame_palette.go")
    with open(out, "w") as f:
        f.write("// Generated by gen_mame_palette.py — do not edit. MAME's actual\n"
                "// a2600 (NTSC) and a2600p (PAL) RGB per TIA colour code (256*3\n"
                "// bytes; index = colour byte; odd/0 = black). Used to reverse-map\n"
                "// MAME's rendered pixels to TIA codes per region.\n\n"
                "package main\n")
        for var, rgb in tables.items():
            f.write(f"\nvar {var} = [768]byte{{" + ",".join(str(b) for b in rgb) + "}\n")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
